
# sublime_api core interface

active_window()
architecture()
cache_path()
can_accept_input(self.name(), args)
channel()
decode_value(data)
encode_value(val, pretty)
error_message(msg)
executable_path()
expand_variables(val, variables)
find_resources(pattern)
get_clipboard(size_limit)
get_macro()
installed_packages_path()
load_binary_resource(name)
load_resource(name)
load_settings(base_name)
log_build_systems(flag)
log_commands(flag)
log_indexing(flag)
log_input(flag)
log_message(s)
log_result_regex(flag)
message_dialog(msg)
notify_application_commands(cmds)
ok_cancel_dialog(msg, ok_title)
packages_path()
platform()
run_command(cmd, args)
save_settings(base_name)
score_selector(scope_name, selector)
set_clipboard(text)
set_timeout(f, timeout_ms)
set_timeout_async(f, timeout_ms)
settings_add_on_change(self.settings_id, tag, callback)
settings_clear_on_change(self.settings_id, tag)
settings_erase(self.settings_id, key)
settings_get(self.settings_id, key)
settings_get_default(self.settings_id, key, default)
settings_has(self.settings_id, key)
settings_set(self.settings_id, key, value)
sheet_view(self.sheet_id)
sheet_window(self.sheet_id)
status_message(msg)
version()
view_add_phantom(self.view_id, key, region, content, layout, on_navigate)
view_add_regions(self.view_id, key, regions, scope, icon, flags)
view_assign_syntax(self.view_id, syntax_file)
view_begin_edit(self.view_id, edit_token, cmd, args)
view_buffer_id(self.view_id)
view_buffer_id(self.view_id) != 0
view_cached_substr(self.view_id, x, x + 1)
view_cached_substr(self.view_id, x.a, x.b)
view_can_accept_input(self.view.id(), self.name(), args)
view_change_count(self.view_id)
view_classify(self.view_id, pt)
view_command_history(self.view_id, delta, modifying_only)
view_em_width(self.view_id)
view_encoding(self.view_id)
view_end_edit(self.view_id, edit.edit_token)
view_erase(self.view_id, edit.edit_token, r)
view_erase_phantom(self.view_id, pid)
view_erase_phantoms(self.view_id, key)
view_erase_regions(self.view_id, key)
view_erase_status(self.view_id, key)
view_expand_by_class(self.view_id, x, x, classes, separators)
view_expand_by_class(self.view_id, x.a, x.b, classes, separators)
view_extract_completions(self.view_id, prefix, tp)
view_extract_scope(self.view_id, pt)
view_extract_tokens_with_scopes(self.view_id, r.begin(), r.end()
view_file_name(self.view_id)
view_find(self.view_id, pattern, start_pt, flags)
view_find_all(self.view_id, pattern, flags)
view_find_all_results(self.view_id)
view_find_all_results_with_text(self.view_id)
view_find_all_with_contents(self.view_id, pattern, flags, fmt)
view_find_by_class(self.view_id, pt, forward, classes, separators)
view_find_by_selector(self.view_id, selector)
view_fold_region(self.view_id, x)
view_fold_regions(self.view_id, x)
view_folded_regions(self.view_id)
view_full_line_from_point(self.view_id, x)
view_full_line_from_region(self.view_id, x)
view_get_name(self.view_id)
view_get_overwrite_status(self.view_id)
view_get_regions(self.view_id, key)
view_get_status(self.view_id, key)
view_has_non_empty_selection_region(self.view_id)
view_hide_popup(self.view_id)
view_indentation_level(self.view_id, pt)
view_indented_region(self.view_id, pt)
view_indexed_references(self.view_id)
view_indexed_symbols(self.view_id)
view_insert(self.view_id, edit.edit_token, pt, text)
view_is_auto_complete_visible(self.view_id)
view_is_dirty(self.view_id)
view_is_folded(self.view_id, sr)
view_is_in_edit(self.view_id)
view_is_loading(self.view_id)
view_is_popup_visible(self.view_id)
view_is_primary(self.view_id)
view_is_read_only(self.view_id)
view_is_scratch(self.view_id)
view_layout_extents(self.view_id)
view_layout_to_text(self.view_id, xy)
view_layout_to_window(self.view_id, xy)
view_line_endings(self.view_id)
view_line_from_point(self.view_id, x)
view_line_from_region(self.view_id, x)
view_line_height(self.view_id)
view_lines(self.view_id, r)
view_match_selector(self.view_id, pt, selector)
view_meta_info(self.view_id, key, pt)
view_query_phantoms(self.view_id, [pid])
view_query_phantoms(self.view_id, pids)
view_replace(self.view_id, edit.edit_token, r, text)
view_reset_reference_document(self.view_id)
view_retarget(self.view_id, new_fname)
view_row_col(self.view_id, tp)
view_run_command(self.view_id, cmd, args)
view_scope_name(self.view_id, pt)
view_score_selector(self.view_id, pt, selector)
view_selection_add_point(self.view_id, x)
view_selection_add_region(self.view_id, x.a, x.b, x.xpos)
view_selection_clear(self.view_id)
view_selection_contains(self.view_id, region.a, region.b)
view_selection_erase(self.view_id, index)
view_selection_get(self.view_id, index)
view_selection_size(self.view_id)
view_selection_subtract_region(self.view_id, region.a, region.b)
view_set_encoding(self.view_id, encoding_name)
view_set_line_endings(self.view_id, line_ending_name)
view_set_name(self.view_id, name)
view_set_overwrite_status(self.view_id, value)
view_set_read_only(self.view_id, read_only)
view_set_reference_document(self.view_id, reference)
view_set_scratch(self.view_id, scratch)
view_set_status(self.view_id, key, value)
view_set_viewport_position(self.view_id, xy, animate)
view_settings(self.view_id)
view_show_point(self.view_id, x, show_surrounds)
view_show_point_at_center(self.view_id, x)
view_show_popup(
view_show_popup_table(self.view_id, items, on_select, flags, -1)
view_show_region(self.view_id, i, show_surrounds)
view_show_region(self.view_id, x, show_surrounds)
view_show_region_at_center(self.view_id, x)
view_size(self.view_id)
view_split_by_newlines(self.view_id, r)
view_style(self.view_id)
view_style_for_scope(self.view_id, scope)
view_symbols(self.view_id)
view_text_point(self.view_id, row, col)
view_text_to_layout(self.view_id, tp)
view_unfold_region(self.view_id, x)
view_unfold_regions(self.view_id, x)
view_update_popup_content(self.view_id, content)
view_viewport_extents(self.view_id)
view_viewport_position(self.view_id)
view_visible_region(self.view_id)
view_window(self.view.id(),
view_window(self.view_id)
view_window_to_layout(self.view_id, xy)
view_word_from_point(self.view_id, x)
view_word_from_region(self.view_id, x)
window_active_group(self.window_id)
window_active_panel(self.window_id)
window_active_sheet(self.window_id)
window_active_sheet_in_group(self.window_id, group)
window_active_view(self.window_id)
window_active_view(w.window_id)
window_active_view_in_group(self.window_id, group)
window_can_accept_input(self.window.id(), self.name(), args)
window_close_file(window_id, self.view_id)
window_create_output_panel(self.window_id, name, unlisted)
window_destroy_output_panel(self.window_id, name)
window_extract_variables(self.window_id)
window_find_open_file(self.window_id, fname)
window_find_output_panel(self.window_id, name)
window_focus_group(self.window_id, idx)
window_focus_sheet(self.window_id, sheet.sheet_id)
window_focus_view(self.window_id, view.view_id)
window_folders(self.window_id)
window_get_layout(self.window_id)
window_get_project_data(self.window_id)
window_get_sheet_index(self.window_id, sheet.sheet_id)
window_get_view_index(self.window_id, view.view_id)
window_is_ui_element_visible(self.window_id, UI_ELEMENT_MENU)
window_is_ui_element_visible(self.window_id, UI_ELEMENT_MINIMAP)
window_is_ui_element_visible(self.window_id, UI_ELEMENT_SIDE_BAR)
window_is_ui_element_visible(self.window_id, UI_ELEMENT_STATUS_BAR)
window_is_ui_element_visible(self.window_id, UI_ELEMENT_TABS)
window_lookup_references(self.window_id, sym)
window_lookup_references_in_open_files(self.window_id, sym)
window_lookup_symbol(self.window_id, sym)
window_lookup_symbol_in_open_files(self.window_id, sym)
window_new_file(self.window_id, flags, syntax)
window_num_groups(self.window_id)
window_num_groups(self.window_id) != 0
window_open_file(self.window_id, fname, flags, group)
window_panels(self.window_id)
window_project_file_name(self.window_id)
window_run_command(
window_run_command(self.window_id, cmd, args)
window_set_layout(self.window_id, layout)
window_set_project_data(self.window_id, v)
window_set_sheet_index(self.window_id, sheet.sheet_id, group, idx)
window_set_ui_element_visible(self.window_id, UI_ELEMENT_MENU, flag)
window_set_ui_element_visible(self.window_id, UI_ELEMENT_MINIMAP, flag)
window_set_ui_element_visible(self.window_id, UI_ELEMENT_SIDE_BAR, flag)
window_set_ui_element_visible(self.window_id, UI_ELEMENT_STATUS_BAR, flag)
window_set_ui_element_visible(self.window_id, UI_ELEMENT_TABS, flag)
window_set_view_index(self.window_id, view.view_id, group, idx)
window_settings(self.window_id)
window_sheets(self.window_id)
window_sheets_in_group(self.window_id, group)
window_show_input_panel(
window_show_quick_panel(
window_status_message(self.window_id, msg)
window_system_handle(self.window_id)
window_template_settings(self.window_id)
window_transient_sheet_in_group(self.window_id, group)
window_transient_view_in_group(self.window_id, group)
window_views(self.window_id)
window_views_in_group(self.window_id, group)
yes_no_cancel_dialog(msg, yes_title, no_title)

